name: Check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Nix
        uses: https://github.com/cachix/install-nix-action@v31

      - name: Check formatting
        run: nix develop --command nixfmt --check flake.nix nix/*.nix nix/modules/*.nix tests/*.nix

      - name: Evaluate flake
        run: nix flake check --no-build --all-systems --show-trace
